### ISSUE TITLE
training question

### ISSUE THREAD

**Issue by penetratef** [Laz4rz/MulticlassBrainSegmentation#1]
Can share loss function and model code ? 
I can't run train4.py because loss and model not import , I try other dice_loss and Unet model ,but still can't training ,thanks

**Comment by Laz4rz** [comment]
Hey, I'll try to upload the rest of the code when I get back on Monday.

**Comment by penetratef** [comment]
> Hey, I'll try to upload the rest of the code when I get back on Monday.

ok, thanks

**Comment by penetratef** [comment]
Please confirm whether the rest of code is uploaded. I can't see that , thanks

**Comment by penetratef** [comment]
I can't see the rest of upload code. Please confirm if there is an upload, thanks
